#!/bin/sh

echo you need at least:
echo autoconfig 2.57
echo automake 1.7.6
echo libtool 1.4.3

set -e
set -x
if test -f Makefile; then
	make distclean
fi
rm -rf *.cache *.status *.log *.m4
autoreconf --verbose --install
